### ISSUE TITLE
Tool not working/blank screen instead of picture

### ISSUE THREAD

**Issue by Moesam961** [sapic/avatarcropper#26]
So, I am a frequent user of the site so noticed this issue early on (When the visuals changed/new features were added is when I noticed the issue that's became prevalent and happens at every use of the site) But basically the square cropping tool 70% of the time does not work, but instead will show me a blank screen where the image should have loaded. When I click download when it appears this way, it just downloads a completely transparent/blank image. 

Neither re-opening the image/sight or re-cropping will stop the issue, and the only fix iv noticed is moving around/resizing the cropper which can take several tries

**Comment by TheOddball** [comment]
This issue was re submitted from a Discord ticket. I will require the browser console log.
