### ISSUE TITLE
avatarcropper.com has expired

### ISSUE THREAD

**Issue by qixils** [sapic/avatarcropper#33]
http://avatarcropper.com/ -> http://domain-registrar.storage.googleapis.com/expired.html?avatarcropper.com

![image](https://github.com/sapic/avatarcropper/assets/13265322/9ada1f26-ff46-46b8-a24b-34e0f4dfe758)

**Comment by SlippingGitty** [comment]
<img width="553" alt="image" src="https://github.com/sapic/avatarcropper/assets/76500838/8bec4c58-e3f7-442e-b0f8-5e99b5c49e42">
my fault ya'll im sorry
